marketplace: bestbuy
name: CAT_1006
headers_file: ../../../templates/bestbuy/CAT_1006.csv
fields:
  BBYCat:
    from_category:
      marketplace: bestbuy
  shop_sku:
    from_submission: sku
  _Title_BB_Category_Root_EN:
    transform: bb_title
    pipeline:
      - replace:
          " - ": ", "
  _Short_Description_BB_Category_Root_EN:
    transform: export_features_bullets
  _Brand_Name_Category_Root_EN:
    from: identity.brand
  _Primary_UPC_Category_Root_EN:
    from_submission: upc
  _Model_Number_Category_Root_EN:
    from: identity.model
  _Manufacturers_Part_Number_Category_Root_EN:
    from: identity.mpn
  _Long_Description_BB_Category_Root_EN:
    transform: bb_long_description
    design_heading: "Feature & Design:"
    spec_heading: "Specifications:"
  _MP_Source_Image_URL_01_Category_Root_EN:
    transform: scraped_image_url
    image_index: 1
  _MP_Source_Image_URL_02_Category_Root_EN:
    transform: scraped_image_url
    image_index: 2
  _MP_Source_Image_URL_03_Category_Root_EN:
    transform: scraped_image_url
    image_index: 3
  _MP_Source_Image_URL_04_Category_Root_EN:
    transform: scraped_image_url
    image_index: 4
  _MP_Source_Image_URL_05_Category_Root_EN:
    transform: scraped_image_url
    image_index: 5
  _MP_Source_Image_URL_06_Category_Root_EN:
    transform: scraped_image_url
    image_index: 6
  _MP_Source_Image_URL_07_Category_Root_EN:
    transform: scraped_image_url
    image_index: 7
  _MP_Source_Image_URL_08_Category_Root_EN:
    transform: scraped_image_url
    image_index: 8
  _MP_Source_Image_URL_09_Category_Root_EN:
    transform: scraped_image_url
    image_index: 9
  _MP_Source_Image_URL_10_Category_Root_EN:
    transform: scraped_image_url
    image_index: 10
  _Web_Hierarchy_Location_Category_Root_EN:
    literal: ''
  _French_Compliant_Category_Root_EN:
    literal: ''
  _ESRB_Category_Root_EN:
    literal: ""
    allowed: [ "", "C", "R", "P", "O", "M", "A", "E", "S", "T" ]
  _Software_Platform_Category_Root_EN:
    sources:
      - path: software.platform
      - group: Product Information
        key: Platform Supported
      - group: Software
        key: Operating System Platform
    join: " "
  _Energy_Star_Indicator_Category_Root_EN:
    sources:
      - [ "internal", "certification", "energy_star_certified" ]
    transform: spec_y_n
  Variant_Group_Code:
    literal: ''
  _Pim_Code_Category_Root_EN:
    literal: ''
  _Warranty_And_Repair_Disclosure_URL_Category_Root_EN:
    literal: ''
    #    transform: warranty_url_by_brand
  _Warranty_And_Repair_Disclosure_URL_FR_Category_Root_EN:
    literal: ''
  _ProductCondition_20257570_CAT_1006_EN:
    literal: ''
    transform: bb_product_condition
    allowed: [ "Brand New", "Open Box", "Refurbished Excellent", "Refurbished Good", "Refurbished Fair" ]
  _ScreenSize_3914_CAT_1006_EN:
    sources:
      - [ "internal", "display", "size_in" ]
  _RefreshRate_18598_CAT_1006_EN:
    sources:
      - [ "internal", "display", "refresh_rate_hz" ]
    transform: only_digits
  _Resolution_30558_CAT_1006_EN:
    sources:
      - [ "internal", "display", "resolution" ]
  _WhatsintheBox_4667_CAT_1006_EN:
    sources:
      - [ "internal", "included_items" ]
    list_join: ";"
  _Brightness_18563_CAT_1006_EN:
    sources:
      - [ "internal", "display", "brightness_cdm2" ]
    transform: only_digits
  _DisplayType_28393_CAT_1006_EN:
    sources:
      - [ "internal", "display", "display_type" ]
    transform: bb_extract_display_type
    allowed: ["", "LCD", "LED", "OLED"]
  _NativeResolution_28396_CAT_1006_EN:
    sources:
      - [ "internal", "display", "resolution" ]
  _ResponseTimeBlackWhiteBlack_28398_CAT_1006_EN:
    literal: ''
  _BuiltinSpeakers_28399_CAT_1006_EN:
    sources:
      - [ "internal", "audio", "speaker" ]
    transform: spec_yes_no
    allowed: ["", "Yes", "No"]
  _BuiltInTVTuner_28400_CAT_1006_EN:
    sources:
      - [ "internal", "technical", "tv_tuner_presence" ]
    transform: spec_yes_no
    allowed: [ "", "Yes", "No" ]
  _WidthWithoutStand_28404_CAT_1006_EN:
    sources:
      - [ "internal", "physical", "dimensions", "item_without_stand", "width_in" ]
    transform: length_in_to_cm
  _HeightWithoutStand_28405_CAT_1006_EN:
    sources:
      - [ "internal", "physical", "dimensions", "item_without_stand", "height_in" ]
    transform: length_in_to_cm
  _DepthWithoutStand_28406_CAT_1006_EN:
    sources:
      - [ "internal", "physical", "dimensions", "item_without_stand", "depth_in" ]
    transform: length_in_to_cm
  _WeightWithoutStand_28407_CAT_1006_EN:
    sources:
      - [ "internal", "physical", "weight", "item_without_stand_lb" ]
    transform: weight_lb_to_kg
  _MultiTouchPoints_31080_CAT_1006_EN:
    literal: ''
  _GlossyMatte_31081_CAT_1006_EN:
    literal: ''
    allowed: ["", "Glossy", " Matte"]
  _ResponseTimeGreytoGrey_31082_CAT_1006_EN:
    sources:
      - [ "internal", "display", "response_time" ]
  _ColourGamut_31084_CAT_1006_EN:
    literal: ''
  _BuiltInWebcam_31093_CAT_1006_EN:
    sources:
      - [ "internal", "technical", "tv_tuner_presence" ]
    transform: spec_yes_no
    allowed: [ "", "Yes", "No" ]
  _DVIDSupport_31107_CAT_1006_EN:
    literal: ''
    allowed: [ "", "Yes", "No" ]
  _HDCPSupport_31108_CAT_1006_EN:
    transform: check_hdcp
    allowed: [ "", "Yes", "No" ]
  _EnergySavingMode_31117_CAT_1006_EN:
    literal: ''
  _TiltAdjustment_31119_CAT_1006_EN:
    sources:
      - [ "internal", "display", "adjustment", "tilt" ]
    transform: spec_yes_no
    allowed: [ "", "Yes", "No" ]
  _SwivelAdjustment_31120_CAT_1006_EN:
    sources:
      - [ "internal", "display", "adjustment", "swivel" ]
    transform: spec_yes_no
    allowed: [ "", "Yes", "No" ]
  _HeightAdjustment_31121_CAT_1006_EN:
    sources:
      - [ "internal", "display", "adjustment", "height" ]
    transform: spec_yes_no
    allowed: [ "", "Yes", "No" ]
  _RotatetoPortrait_31122_CAT_1006_EN:
    sources:
      - [ "internal", "display", "adjustment", "pivot" ]
    transform: spec_yes_no
    allowed: [ "", "Yes", "No" ]
  _VESAMountable_31123_CAT_1006_EN:
    sources:
      - [ "internal", "technical", "vesa_mount" ]
    transform: spec_yes_no
    allowed: [ "", "Yes", "No" ]
  _VESASizesSupported_31124_CAT_1006_EN:
    sources:
      - [ "internal", "technical", "vesa_mount_size" ]
    list_join: ";"
  _WidthWithStand_31126_CAT_1006_EN:
    sources:
      - [ "internal", "physical", "dimensions", "item_with_stand", "highest_position", "width_in" ]
    transform: length_in_to_cm
  _DepthWithStand_31128_CAT_1006_EN:
    sources:
      - [ "internal", "physical", "dimensions", "item_with_stand", "highest_position", "length_in" ]
    transform: length_in_to_cm
  _WeightWithStand_31129_CAT_1006_EN:
    sources:
      - [ "internal", "physical", "weight", "item_with_stand_lb" ]
    transform: weight_lb_to_kg
  _Curved_39638_CAT_1006_EN:
    sources:
      - [ "internal", "display", "curve_screen" ]
    transform: spec_yes_no
    allowed: [ "", "Yes", "No" ]
  _AspectRatio_9471_CAT_1006_EN:
    sources:
      - [ "internal", "display", "aspect_ratio" ]
  _AutoOff_19703_CAT_1006_EN:
    literal: ''
  _BacklightType_19653_CAT_1006_EN:
    sources:
      - [ "internal", "display", "backlight_technology" ]
  _Colour_5105_CAT_1006_EN:
    sources:
      - [ "internal", "physical", "color" ]
      - [ "internal", "physical", "color_category" ]
    join: ";"
  _DynamicContrastRatio_18588_CAT_1006_EN:
    literal: ''
  _OtherFeatures_26219_CAT_1006_EN:
    sources:
      - [ "internal", "display", "features" ]
      - [ "internal", "technical", "features" ]
    list_join: ";"
  _SpeakerOutputPower_13985_CAT_1006_EN:
    sources:
      - [ "internal", "display", "speaker_output_power_watt" ]
    suffix: ' watt'
  _StandByConsumption_19702_CAT_1006_EN:
    sources:
      - [ "internal", "power", "consumption_watt", "standby" ]
  _StaticContrastRatio_18562_CAT_1006_EN:
    sources:
      - [ "internal", "display", "static_contrast_ratio" ]
  _Touchscreen_19922_CAT_1006_EN:
    sources:
      - [ "internal", "display", "touchscreen" ]
    transform: spec_yes_no
    allowed: [ "", "Yes", "No" ]
  _TypicalConsumption_19701_CAT_1006_EN:
    sources:
      - [ "internal", "power", "consumption_watt", "typical" ]
  _ViewingAngle_10316_CAT_1006_EN:
    sources:
      - [ "internal", "display", "horizontal_viewing_angle" ]
      - [ "internal", "display", "horizontal_viewing_angle" ]
    join: 'º (H) / '
    suffix: 'º (V)'
  _3DVideoSupportBuiltin_31091_CAT_1006_EN:
    literal: ''
  _HeightWithStand_852161_CAT_1006_EN:
    sources:
      - [ "internal", "physical", "dimensions", "item_with_stand", "height_in" ]
  _PanelTechnology_1536229_CAT_1006_EN:
    sources:
      - [ "internal", "display", "panel" ]
  _PanelType_31078_CAT_1006_EN:
    sources:
      - [ "internal", "display", "panel" ]
  _InputOutputTypes_28401_CAT_1006_EN:
    sources:
      - [ "internal", "io", "interfaces" ]
    join: ";"
  _ENERGYSTARcertified_22372173_CAT_1006_EN:
    sources:
      - [ "internal", "certification", "energy_star_certified" ]
    transform: spec_yes_no
  sku:
    from_submission: sku
  product-id:
    from_submission: sku
  product-id-type:
    literal: "SHOP_SKU"
  description:
    literal: ''
  internal-description:
    literal: ''
  price:
    from_submission: marketplaces.bestbuy.list_price
  price-additional-info:
    literal: ''
  quantity:
    literal: 0
    type: integer
  min-quantity-alert:
    literal: ''
  state:
    literal: "11"
  available-start-date:
    literal: ''
  available-end-date:
    literal: ''
  logistic-class:
    from_submission: marketplaces.bestbuy.package_size
  discount-price:
    from_submission: price
    type: decimal
    decimals: 2
    default: FILL
  discount-start-date:
    from_submission: marketplaces.bestbuy.discount_start_date
    suffix: "T00:00:00.000-07:00"
  discount-end-date:
    from_submission: marketplaces.bestbuy.discount_end_date
    suffix: "T23:59:59.999-07:00"
  update-delete:
    literal: "UPDATE"
  manufacturer-warranty:
    literal: 365
    type: integer
  pim:
    literal: ''
