marketplace: bestbuy
name: CAT_314802
headers_file: ../../../templates/bestbuy/CAT_314802-example.csv
fields:
  BBYCat:
    from_category:
      marketplace: bestbuy
  shop_sku:
    from_submission: sku
  _Title_BB_Category_Root_EN:
    transform: bb_title
    pipeline:
      - replace:
          " - ": ", "
  _Short_Description_BB_Category_Root_EN:
    transform: export_features_bullets
  _Brand_Name_Category_Root_EN:
    from: identity.brand
  _Primary_UPC_Category_Root_EN:
    from_submission: upc
  _Model_Number_Category_Root_EN:
    from: identity.model
  _Manufacturers_Part_Number_Category_Root_EN:
    from: identity.mpn
  _Long_Description_BB_Category_Root_EN:
    transform: bb_long_description
    design_heading: "Feature & Design:"
    spec_heading: "Specifications:"
  _MP_Source_Image_URL_01_Category_Root_EN:
    transform: scraped_image_url
    image_index: 1
  _MP_Source_Image_URL_02_Category_Root_EN:
    transform: scraped_image_url
    image_index: 2
  _MP_Source_Image_URL_03_Category_Root_EN:
    transform: scraped_image_url
    image_index: 3
  _MP_Source_Image_URL_04_Category_Root_EN:
    transform: scraped_image_url
    image_index: 4
  _MP_Source_Image_URL_05_Category_Root_EN:
    transform: scraped_image_url
    image_index: 5
  _MP_Source_Image_URL_06_Category_Root_EN:
    transform: scraped_image_url
    image_index: 6
  _MP_Source_Image_URL_07_Category_Root_EN:
    transform: scraped_image_url
    image_index: 7
  _MP_Source_Image_URL_08_Category_Root_EN:
    transform: scraped_image_url
    image_index: 8
  _MP_Source_Image_URL_09_Category_Root_EN:
    transform: scraped_image_url
    image_index: 9
  _MP_Source_Image_URL_10_Category_Root_EN:
    transform: scraped_image_url
    image_index: 10
  _Web_Hierarchy_Location_Category_Root_EN:
    literal: ''
  _French_Compliant_Category_Root_EN:
    literal: ''
  _ESRB_Category_Root_EN:
    literal: ""
    allowed: [ "", "C", "R", "P", "O", "M", "A", "E", "S", "T" ]
  _Software_Platform_Category_Root_EN:
    sources:
      - path: software.platform
      - group: Product Information
        key: Platform Supported
      - group: Software
        key: Operating System Platform
    join: " "
  _Energy_Star_Indicator_Category_Root_EN:
    sources:
      - [ "internal", "certification", "energy_star_certified" ]
    transform: spec_y_n
  Variant_Group_Code:
    literal: ''
  _Pim_Code_Category_Root_EN:
    literal: ''
  _Warranty_And_Repair_Disclosure_URL_Category_Root_EN:
    literal: ''
    #    transform: warranty_url_by_brand
  _Warranty_And_Repair_Disclosure_URL_FR_Category_Root_EN:
    literal: ''
  _ScreenSize_3914_CAT_29958_EN:
    sources:
      - [ "internal", "display", "size_in" ]
  _WhatsintheBox_4667_CAT_29958_EN:
    sources:
      - [ "internal", "included_items" ]
    list_join: ";"
  _DLNACertified_19688_CAT_29958_EN:
    literal: ''
  _FrontCameraAutofocus_25403_CAT_29958_EN:
  _FrontCameraFlash_25404_CAT_29958_EN:
  _VideoCallingWiFi_25405_CAT_29958_EN:
  _VideoCallingCellular_25406_CAT_29958_EN:
  _OperatingSystem_25414_CAT_29958_EN:
  _PreloadedSoftware_25415_CAT_29958_EN:
  _AppStoreCompatibility_25417_CAT_29958_EN:
  _CellularProvider_25430_CAT_29958_EN:
  _HDMIOutput_25433_CAT_29958_EN:
  _HeightInches_25131_CAT_29958_EN:
  _IntegratedBluetooth_15246_CAT_29958_EN:
  _IntegratedMicrophone_15207_CAT_29958_EN:
  _MicrophoneInput_15208_CAT_29958_EN:
  _NativeScreenResolution_15917_CAT_29958_EN:
  _OtherInputsOutputs_18576_CAT_29958_EN:
  _ProcessorCores_23322_CAT_29958_EN:
  _ProcessorType_3885_CAT_29958_EN:
  _Sensors_8727_CAT_29958_EN:
  _Stylus_15607_CAT_29958_EN:
  _UnassistedGPSNavigation_21902_CAT_29958_EN:
  _Weight_6612_CAT_29958_EN:
  _Width_6823_CAT_29958_EN:
  _WidthInches_25132_CAT_29958_EN:
  _BuiltinStorageType_25391_CAT_29958_EN:
  _CompatibleMemoryCardTypes_25393_CAT_29958_EN:
  _RearCameraVideoResolution_25398_CAT_29958_EN:
  _RearCameraAutofocus_25399_CAT_29958_EN:
  _RearCameraFlash_25400_CAT_29958_EN:
  _FrontCameraVideoResolution_25401_CAT_29958_EN:
  _Multitasking_42788_CAT_29958_EN:
  _AssistedGPSNavigation_21901_CAT_29958_EN:
  _BatteryCapacity_15253_CAT_29958_EN:
  _BuiltinMemoryCardReader_15230_CAT_29958_EN:
  _BuiltinSpeaker_19941_CAT_29958_EN:
  _BuiltinStand_24740_CAT_29958_EN:
  _ChargeoverUSB_21951_CAT_29958_EN:
  _Depth_14236_CAT_29958_EN:
  _DepthInches_25133_CAT_29958_EN:
  _HardwareVolumeControl_15211_CAT_29958_EN:
  _Height_15404_CAT_29958_EN:
  _HeadphoneJack_6432_CAT_29958_EN:
  _MaxMemoryCardCapacity_33514_CAT_29958_EN:
  _OperatingSystemLanguage_15257_CAT_29958_EN:
  _ProcessorSpeed_3886_CAT_29958_EN:
  _YearofOriginalRelease_12007740_CAT_29958_EN:
  _SpeakerWattage_16519892_CAT_29958_EN:
  _ScreenFinish_16519920_CAT_29958_EN:
  _RearCameraStillResolution_16519889_CAT_29958_EN:
  _FrontCameraStillResolution_16519884_CAT_29958_EN:
  _ApproximateStandbyBatteryLife_16519878_CAT_29958_EN:
  _ApproximateInuseBatteryLife_16519876_CAT_29958_EN:
  _RAMType_24674_CAT_29958_EN:
  _BuiltinStorageCapacity_21097759_CAT_29958_EN:
  _MicrosoftOfficeCompatible_42787_CAT_29958_EN:
  _RAMSize_26545701_CAT_29958_EN:
  _WiFiStandards_26475847_CAT_29958_EN:
  _IntegratedWiFi_26690001_CAT_29958_EN:
  _CellularConnectivity_26690318_CAT_29958_EN:
  _DisplayTechnology_26908001_CAT_29958_EN:
  _StylusSupport_26923159_CAT_29958_EN:
  _KeyboardCompatibility_26923256_CAT_29958_EN:
  _ProductCondition_20257570_CAT_314802_EN:
  _NumberofUSBTypeCPorts_17216491_CAT_314802_EN:
  _NumberofUSBTypeAPorts_17216494_CAT_314802_EN:
  _GraphicsCard_15196_CAT_314802_EN:
  _NumberofUSBPortsTotal_31805_CAT_314802_EN:
  _PreinstalledVoiceAssistant_19775045_CAT_314802_EN:
  _CopilotPC_23854063_CAT_314802_EN:
  _ComboPack_18730731_CAT_314802_EN:
  _Colour_5105_CAT_314802_EN:
  _Model_20123681_CAT_314802_EN:
  sku:
  product-id:
  product-id-type:
  description:
  internal-description:
  price:
  price-additional-info:
  quantity:
  min-quantity-alert:
  state:
  available-start-date:
  available-end-date:
  logistic-class:
  discount-price:
  discount-start-date:
  discount-end-date:
  leadtime-to-ship:
  update-delete:
  manufacturer-warranty:
  pim: