marketplace: newegg
name: MonitorLCDFlatPanel
headers_file: ../../../templates/newegg/ComputerHardware_BatchItemCreation_MonitorLCDFlatPanel.csv
csv_preamble_row:
  - Version=1.01
  - SubCategoryID=20
  - ""
  - TemplateDate=2026-06-21

fields:
  'Seller Part #':
    from_submission: sku
  Manufacturer:
    from_submission: manufacturer
    transform: get_brand_label
  'Manufacturer Parts #':
    from: identity.mpn
  UPC / ISBN:
    from_submission: upc
  Related Seller Part#:
    literal: ''
  Website Short Title:
    pipeline:
      - transform: ne_title
    #      - replace: #replace in function
    #          " - ": ", "
  Bullet Description:
    transform: export_features
  Product Description:
    transform: ne_long_description
    design_heading: "Feature & Design:"
    spec_heading: "Specifications:"
  Item Length:
    sources:
      - [ "internal", "physical", "dimensions", "package", "length_in" ]
      - [ "internal", "physical", "dimensions", "item", "length_in" ]
  Item Width:
    sources:
      - [ "internal", "physical", "dimensions", "package", "width_in" ]
      - [ "internal", "physical", "dimensions", "item", "width_in" ]
  Item Height:
    sources:
      - [ "internal", "physical", "dimensions", "package", "height_in" ]
      - [ "internal", "physical", "dimensions", "item", "height_in" ]
  Item Weight:
    sources:
      - [ "internal", "physical", "weight", "package_lb" ]
      - [ "internal", "physical", "weight", "item_lb" ]
  Packs Or Sets:
    literal: 1
    #    sources:
    #      - ["internal", "physical", "packaged_qty"]
    #    default: 1
    #    type: integer
  Item Condition:
    transform: ne_product_condition
    allowed: [ "", "New", "Refurbished", "UsedLikeNew", "UsedVeryGood" , "UsedGood", "UsedAcceptable" ]
  Item Package:
    literal: "Retail"
    allowed: [ "Retail", "OEM" ]
  Shipping Restriction:
    literal: ''
  Currency:
    literal: ''
  MSRP:
    literal: ''
  MAP:
    literal: ''
  CheckoutMAP:
    literal: ''
    allowed: [ "", "True", "False" ]
  Selling Price:
    from_submission: price
  Shipping:
    from_submission: marketplaces.newegg.shipping_type
    allowed: [ "Free", "Default" ]
  Inventory:
    literal: 0
  Limit Quantity:
    literal: ''
  Activation Mark:
    literal: 'TRUE'
    allowed: [ "", "TRUE", "FALSE" ]
  Action:
    literal: 'Create Item'
    allowed: [ "", "Create Item", "Update Item", "Update/Append Image", "Replace Image" ]
  Item Images:
    sources:
      - [ "internal", "content", "images" ]
    list_join: ","
  Condition Details:
    literal: ''
  Used Item Images:
    literal: ''
  Country Of Origin:
    literal: ''
  Age 18+ Verification:
    literal: ''
  Choking Hazard 1:
    literal: ''
  Choking Hazard 2:
    literal: ''
  Choking Hazard 3:
    literal: ''
  Choking Hazard 4:
    literal: ''
  Lead Time:
    literal: ''
  Shipping Template:
    literal: ''
  Custom Variety 1 Name:
    literal: ''
  Custom Variety 1 Value:
    literal: ''
  Custom Variety 2 Name:
    literal: ''
  Custom Variety 2 Value:
    literal: ''
  Custom Variety 3 Name:
    literal: ''
  Custom Variety 3 Value:
    literal: ''
  MonitorModelModel:
    sources:
      - [ "internal", "identity", "model" ]
  MonitorModelCabinetColor:
    sources:
      - [ "internal", "physical", "color" ]
  MonitorDisplayPanel:
    sources:
      - [ "internal", "display", "panel" ]
  MonitorDisplayDisplayType:
    sources:
      - [ "internal", "display", "video_format" ]
  MonitorDisplayDisplayColors:
    sources:
      - [ "internal", "display", "color_support" ]
  MonitorDisplayViewingAngle:
    sources:
      - [ "internal", "display", "horizontal_viewing_angle" ]
      - [ "internal", "display", "horizontal_viewing_angle" ]
    join: 'º (H) / '
    suffix: 'º (V)'
  MonitorDisplayMaximumResolution:
    sources:
      - [ "internal", "display", "resolution" ]
  MonitorDisplayHorizontalRefreshRate:
    sources:
      - [ "internal", "display", "refresh_rate_hz" ]
    suffix: " Hz"
  MonitorDisplayVerticalRefreshRate:
    literal: ''
  MonitorConnectivityConnectors:
    sources:
      - [ "internal", "io", "interfaces" ]
    filter_include_keywords: [ "d-sub", "dsub", "bnc", "hdmi", "dvi", "usb", "displayport", "display port", "mhl", "s-video" ]
  MonitorPowerComplieswith:
    sources:
      - [ "internal", "certification", "energy_star_version" ]
    prefix: "Energy Star "
  MonitorPowerPowerSupply:
    sources:
      - [ "internal", "power", "voltage_required" ]
      - [ "internal", "certification", "frequency_hz" ]
    join: ', '
  MonitorPowerPowerConsumption:
    literal: ''
  MonitorConvenienceUserControls:
    literal: ''
  MonitorConvenienceRegulatoryApprovals:
    literal: ''
  MonitorDimensionsDimensions:
    sources:
      - [ "internal", "physical", "dimensions", "item", "width_in" ]
      - [ "internal", "physical", "dimensions", "item", "length_in" ]
      - [ "internal", "physical", "dimensions", "item", "height_in" ]
    join: ' x '
  MonitorDimensionsWeight:
    sources:
      - [ "internal", "physical", "weight", "item_lb" ]
    transform: ne_check_item_weight_scale
  MonitorDimensionsTemperatureRange:
    literal: ''
  MonitorDimensionsHumidityRange:
    source: [ "internal", "technical", "operating_humidity" ]
  MonitorConvenienceFeatures:
    sources:
      - [ "internal", "audio", "output_features" ]
      - [ "internal", "io", "usb_c_features" ]
      - [ "internal", "io", "input_device_features" ]
      - [ "internal", "network", "features" ]
    join: ", "
  MonitorDisplayResolution:
    sources:
      - [ "internal", "display", "resolution" ]
  MonitorConvenienceBuilt-inSpeakers:
    sources:
      - [ "internal", "audio", "speaker" ]
    transform: spec_yes_no
  MonitorConnectivityInputVideoCompatibility:
    literal: ''
  MonitorDisplayAspectRatio:
    sources:
      - [ "internal", "display", "aspect_ratio" ]
  MonitorModelBrand:
    from_submission: manufacturer
    transform: get_brand_label
  MonitorDisplayD-Sub:
    sources:
      - [ "internal", "io", "interface" ]
    filter_include_keywords: [ "dsub", "d-sub" ]
  MonitorDisplayDVI:
    sources:
      - [ "internal", "io", "interface" ]
    filter_include_keywords: [ "dvi" ]
  MonitorDisplayVideo:
    literal: ''
  CommonPackageContents:
    sources:
      - path: included_items
        join: ", "
    template: "{mpn};{value}"
  MonitorDisplayHDMI:
    sources:
      - [ "internal", "io", "interface" ]
    filter_include_keywords: [ "hdmi" ]
  MonitorConvenienceBuilt-inTVTuner:
    sources:
      - [ "internal", "technical", "tv_tuner_presence" ]
    transform: spec_yes_no
    allowed: [ "", "Yes", "No" ]
  MonitorConvenienceStandAdjustments:
    transform: ne_monitor_convenience_stand_adjustments
  MonitorDisplayWidescreen:
    source: [ "internal", "display", "widescreen" ]
    transform: spec_yes_no
  LCDDisplayScreenSize:
    sources:
      - [ "internal", "display", "size_in" ]
    transform: ne_check_screensize
  LCDDisplayMonitorPixelDensity:
    source: [ "internal", "display", "pixel_pitch_mm" ]
    suffix: ' mm'
  LCDDisplayContrastRatio:
    source: [ "internal", "display", "static_contrast_ratio" ]
  LCDDisplayResponseTime:
    source: [ "internal", "display", "response_time" ]
  LCDDisplayBrightness:
    source: [ "internal", "display", "brightness_cdm2" ]
    suffix: ' cd/m2'
  MonitorDisplayUSB20:
    source: [ "internal", "io", "interfaces" ]
    filter_include_keywords: [ "usb2.0", "usb 2.0" ]
  MonitorModelSeries:
    literal: ''
  ManufacturerWarrantyParts:
    literal: '1 Year'
  ManufacturerWarrantyLabor:
    literal: '1 Year'
  CommonWindowsVista:
    literal: ''
  MonitorConvenienceHDCPSupport:
    transform: check_hdcp
  LCDConsumerAlert:
    literal: ''
  MonitorDisplayDisplayPort:
    source: [ "internal", "io", "ports" ]
    filter_include_keywords: [ "displayport" ]
  MonitorConvenienceBuilt-inWebcam:
    sources:
      - [ "internal", "camera", "webcam" ]
    transform: spec_yes_no
  MonitorDisplayGlareScreen:
    transform: check_anti_glare
  MonitorDisplayLEDBacklight:
    literal: ''
  MonGlobal3DReady:
    literal: ''
  MonGlobalRefreshRate:
    sources:
      - [ "internal", "display", "refresh_rate_hz" ]
    suffix: " Hz"
  MonGlobal3DGlassesIncluded:
    literal: ''
  MonitorConvenienceVESACompatibility-Mountable:
    sources:
      - [ "internal", "technical", "vesa_mount_size" ]
    list_join: ","
  MonitorDisplayUSB30:
    source: [ "internal", "io", "interfaces" ]
    filter_include_keywords: [ "usb3.0", "usb 3.0" ]
  MonitorProcessor:
    literal: ''
  MonitorMemory:
    literal: ''
  MonitorOSSupport:
    literal: ''
  MonitorDisplayOLED:
    literal: ''
  MonitorDisplay3DType:
    literal: ''
  MonitorDisplay3DFeatures:
    literal: ''
  MonitorDisplayCurvedSurfaceScreen:
    transform: ne_curved_surface_screen
  MonitorDispalayFrame:
    literal: ''
  GlobalElectricalOutletPlugType:
    literal: ''
  MonitorDisplayAdaptiveSyncTechnology:
    literal: ''
    # Pending
  MonitorDisplayCurvatureRadius:
    literal: ''
    #Pending
  MonitorModelPartNumber:
    from: identity.mpn
  MonitorConnectivityThunderbolt2:
    literal: ''
  MonitorConnectivityThunderbolt3:
    literal: ''
  MonitorDisplayVESACertifiedDisplayHDR:
    sources:
      - [ "internal", "technical", "hdr_certification" ]
  MonitorDisplayHDRStandard:
    literal: ''
    #Pending
    allowed: ["", "HDR10", "HDR10+"]
  MonitorDisplayColorGamut:
    literal: ''
    #pending
  MonitorDisplayHeadphone:
    sources:
      - [ "internal", "io", "interface" ]
    filter_include_keywords: [ "usb" ]
  MultiValueMNTRVideoPorts:
    sources:
      - [ "internal", "io", "interfaces" ]
    filter_include_keywords: [ "d-sub", "dsub", "bnc", "hdmi", "dvi", "usb", "displayport", "display port", "mhl", "s-video" ]
  MultiValueMNTRUSBPorts:
    sources:
      - [ "internal", "io", "interface" ]
    filter_include_keywords: [ "usb" ]
  MonitorModelCosmeticCondition:
    literal: ''
    allowed: ["", "Grade A", "Grade B", "Grade C"]
  UniversalContainsEmbeddedBattery:
    literal: ''
  SimulatorsSimulatorType:
    literal: ''
  SimulatorsPlatform:
    literal: ''
  SimulatorsLayer:
    literal: ''
  SimulatorsBaseCompatibility:
    literal: ''
